# Generated by Django 5.2 on 2025-05-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
