# Generated by Django 5.2 on 2025-05-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
