# Generated by Django 5.2 on 2025-05-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('uz', "O'zbekcha"), ('ru', 'Русский')], max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(unique=True)),
                ('seting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('uz', "O'zbekcha"), ('ru', 'Русский')], max_length=6)),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subject_images/')),
                ('price', models.CharField()),
                ('detail', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('seting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TutorLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subject_images/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tutor')),
            ],
        ),
    ]
