# Generated by Django 5.2 on 2025-05-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_tutorlang_lang_tutorlang_seting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselang',
            old_name='seting',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subjectlang',
            old_name='seting',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='tutorlang',
            old_name='seting',
            new_name='tutor',
        ),
    ]
